"""Initial Migration

Revision ID: 9954b5a32321
Revises: 
Create Date: 2021-01-24 15:10:23.462495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9954b5a32321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tweet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eene', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweet_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
